version: "3.8"
services:
  db:
    image: mysql:3.8-debian
    container_name: mysql_app
    volumes:
      - db_data: /var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend-net
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuser
